### ISSUE TITLE
Changing the demo from the dropdown UI does not update the entry point selector

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang-playground#72]
When you change which demo is loaded, the entry point selector does not update to contain the entry points in the new shader. This will result in a compilation error if you try to compile without clicking on the entry point selector, if the entry points in the newly loaded demo are different from those in the previously loaded one. Ideally, changing the loaded demo should automatically update the entry points in the entry point selector.

**Comment by Devon7925** [comment]
I believe this was fixed in https://github.com/shader-slang/slang-playground/commit/2d9b8420f9747fb1d0e3137f517a7c733e3439f2
